# Generated by Django 4.0.6 on 2022-08-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_student_alter_user_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.TextField()),
                ('cpassword', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
