# Generated by Django 4.0.6 on 2022-08-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_signup_user_delete_student_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_user',
            name='cpassword',
        ),
    ]
