# Generated by Django 4.0.6 on 2022-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0005_signup_user_cpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup_user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='signup_user',
            name='cpassword',
            field=models.TextField(),
        ),
    ]
