# Generated by Django 4.0.6 on 2022-08-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_image_delete_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
