# Generated by Django 4.0.6 on 2022-09-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0006_rename_name_signup_user_username_and_more'),
        ('products', '0004_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='image_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.image')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAccount.signup_user')),
            ],
        ),
    ]
