# Generated by Django 4.0.6 on 2022-09-14 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_image_id_image_image_id_alter_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Image_id',
        ),
    ]
