# Generated by Django 4.0.6 on 2022-09-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_cart_image_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
