# Generated by Django 4.0.6 on 2022-09-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_image_image_id_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
