# Generated by Django 4.0.6 on 2022-09-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_image_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('payment_id', models.IntegerField()),
                ('product_id', models.ImageField(upload_to='')),
            ],
        ),
    ]
