# Generated by Django 4.0.6 on 2022-09-14 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_order_payment_id_alter_order_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
    ]
