# Generated by Django 4.0.6 on 2022-09-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_price_order_amount_remove_order_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
